plugins { id 'com.android.application' }
android { namespace 'org.node.flyconsole'; compileSdk 35
 defaultConfig { applicationId 'org.node.flyconsole.nes'; minSdk 26; targetSdk 35; versionCode 13; versionName '2.0.0-alpha05' }
 compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
}

