package org.node.flyconsole;
import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.webkit.*;
import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;
/** Offline programmable workbench. User/module JS runs only in a disposable Web Worker. */
public final class CodeLabActivity extends Activity {
 private final ExecutorService executor=Executors.newSingleThreadExecutor();private final AtomicBoolean cancel=new AtomicBoolean();private final AtomicLong generation=new AtomicLong();
 private WebView web;private Graph graph;private Engine engine;private volatile boolean destroyed;private String exported="{}";private int requests;
 public void onCreate(Bundle state){super.onCreate(state);web=new WebView(this);web.setBackgroundColor(0xff080a13);web.getSettings().setJavaScriptEnabled(true);web.getSettings().setDomStorageEnabled(true);web.getSettings().setAllowFileAccess(false);web.getSettings().setAllowContentAccess(false);web.getSettings().setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);web.addJavascriptInterface(new Bridge(),"CodeBridge");
  web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){return true;}public WebResourceResponse shouldInterceptRequest(WebView v,WebResourceRequest r){Uri u=r.getUrl();String p=u.getPath();InputStream in=new ByteArrayInputStream(new byte[0]);String mime="text/plain";try{if("https".equals(u.getScheme())&&"flyconsole.local".equals(u.getHost())&&p!=null&&p.startsWith("/code/")&&!p.contains("..")&&"GET".equals(r.getMethod())){in=getAssets().open(p.substring(1));mime=p.endsWith(".js")?"application/javascript":"text/html";}}catch(IOException ignored){}WebResourceResponse out=new WebResourceResponse(mime,"UTF-8",in);Map<String,String> h=new HashMap<>();h.put("Content-Security-Policy","default-src 'none'; script-src 'self' 'unsafe-eval'; worker-src blob:; child-src blob:; style-src 'unsafe-inline'; connect-src 'none'; img-src data:");h.put("X-Content-Type-Options","nosniff");out.setResponseHeaders(h);return out;}});
  setContentView(web);web.loadUrl("https://flyconsole.local/code/index.html");executor.execute(()->{try{graph=GraphCache.current;if(graph==null){File f=new File(getFilesDir(),"connectome.fly");InputStream in;if(f.exists()){in=new FileInputStream(f);GraphCache.kind="Imported graph";}else try{in=getAssets().open("brain.fly.gz");}catch(IOException ex){in=getAssets().open("brain.fly");}long free=Runtime.getRuntime().maxMemory()-Runtime.getRuntime().totalMemory()+Runtime.getRuntime().freeMemory();try(InputStream stream=in){graph=Graph.read(stream,free*2/3);}GraphCache.current=graph;}engine=new Engine(graph);}catch(Exception|OutOfMemoryError ex){graph=null;engine=null;emit("notice",new JSONObject(),"Коннектом не загружен: "+ex.getMessage());}});
 }
 private void emit(String kind,Object value,String error){try{JSONObject r=new JSONObject().put("kind",kind).put("value",value).put("error",error==null?JSONObject.NULL:error);String js="window.codeReceive("+r.toString()+")";runOnUiThread(()->{if(!destroyed)web.evaluateJavascript(js,null);});}catch(Exception ignored){}}
 private void response(long session,int id,Object value,String error){try{emit("reply",new JSONObject().put("session",session).put("id",id).put("data",value),error);}catch(Exception ignored){}}
 public final class Bridge{
  @JavascriptInterface public long begin(){cancel.set(true);long g=generation.incrementAndGet();executor.execute(()->{if(generation.get()==g){cancel.set(false);requests=0;}});return g;}
  @JavascriptInterface public void stop(){generation.incrementAndGet();cancel.set(true);}
  @JavascriptInterface public void request(long session,int id,String method,String payload){if(payload.length()>262144)return;executor.execute(()->{if(session!=generation.get())return;try{if(++requests>64)throw new IOException("Лимит: 64 вызова за запуск");if(graph==null||engine==null)throw new IOException("Дождитесь загрузки коннектома");Object result;
    if("info".equals(method)){JSONArray ids=new JSONArray();for(int i=0;i<Math.min(64,graph.ids.length);i++)ids.put(Long.toString(graph.ids[i]));result=new JSONObject().put("neurons",graph.ids.length).put("edges",graph.targets.length).put("ids",ids).put("dt_ms",.1).put("model",GraphCache.kind);}
    else if("run".equals(method))result=InferenceProgram.run(engine,graph,payload,cancel);
    else throw new IOException("Неизвестный API");if(session==generation.get())response(session,id,result,null);
   }catch(Exception|OutOfMemoryError ex){if(session==generation.get())response(session,id,JSONObject.NULL,ex.getMessage());}});}
  @JavascriptInterface public void pick(String kind){runOnUiThread(()->startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),"module".equals(kind)?1:2));}
  @JavascriptInterface public void export(String content,boolean project){if(content.length()>4194304)return;runOnUiThread(()->{exported=content;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/json").addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_TITLE,project?"fly-project.json":"fly-results.json");startActivityForResult(i,3);});}
  @JavascriptInterface public void navigate(String where){runOnUiThread(()->{cancel.set(true);generation.incrementAndGet();Intent i;if("console".equals(where))i=new Intent(CodeLabActivity.this,MainActivity.class);else{i=new Intent(CodeLabActivity.this,NesLabActivity.class);if("sega".equals(where))i.putExtra("system","sega");}startActivity(i.addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT));});}
 }
 protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();executor.execute(()->{try{if(req==3){try(OutputStream out=getContentResolver().openOutputStream(uri)){out.write(exported.getBytes(StandardCharsets.UTF_8));}emit("notice",new JSONObject(),null);return;}try(InputStream in=getContentResolver().openInputStream(uri)){if(req==1)emit("module",LabModule.read(in),null);else{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1){if(out.size()+n>4194304)throw new IOException("Проект больше 4 МиБ");out.write(b,0,n);}emit("project",new JSONObject(new String(out.toByteArray(),StandardCharsets.UTF_8)),null);}}}catch(Exception ex){emit("notice",new JSONObject(),ex.getMessage());}});}
 protected void onPause(){cancel.set(true);generation.incrementAndGet();if(web!=null)web.evaluateJavascript("window.codeStop&&window.codeStop()",null);super.onPause();}
 protected void onDestroy(){destroyed=true;cancel.set(true);generation.incrementAndGet();executor.shutdownNow();if(web!=null){web.removeJavascriptInterface("CodeBridge");web.destroy();}super.onDestroy();}
}
