'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const Learner=require('../app/src/main/assets/lab/learner.js'),GameTools=require('../app/src/main/assets/lab/game-tools.js');
const NES=require('../app/src/main/assets/lab/jsnes.min.js').NES;
const source=fs.readFileSync('app/src/main/assets/lab/lab.js','utf8');
const rom=Buffer.from(require('../app/src/main/assets/lab/demo-rom.json').base64,'base64').toString('binary');
const core=new NES({onFrame(){},onAudioSample(){}});core.loadROM(rom);for(let i=0;i<10;i++)core.frame();
const nodes={actionMasks:{value:'0,1,2,16,32,64,128,129,17'},inputIds:{value:Array.from({length:16},(_,i)=>String(i+1)).join(',')},outputIds:{value:Array.from({length:8},(_,i)=>String(i+17)).join(',')},lesions:{value:''},fdbJson:{value:''},seed:{value:'1'},windowMs:{value:'20'},maxHz:{value:'150'},thresholdHz:{value:'30'},gain:{value:'1'},backend:{value:'cpu'},mode:{value:'closed'},systemButtons:{value:'blocked'},learnMode:{value:'off'},outputs:{children:[]},play:{},brainToggle:{},resetNes:{},loadState:{}};
const calls=[];const nativeState={tick:12345,fdbRevision:9};
const state={$:id=>nodes[id]||(nodes[id]={value:'',checked:false}),window:{},nes:core,loaded:true,ready:true,playing:false,connected:true,configuring:false,romLoading:false,frame:10,generation:1,pendingToken:null,manualMask:0,brainMask:0,appliedMask:0,appliedHumanMask:0,appliedAgentMask:0,holding:new Map(),audioRead:0,audioWrite:100,frozen:null,gmodeMode:'off',benchmark:null,labPlatform:'nes',romHash:'own',graphIdentity:{sha256:'graph'},requestedConfiguration:null,configurationApplied:true,learner:new Learner(1),FlyGameTools:GameTools,nativeCall:(op,...args)=>{calls.push(op);if(op==='configure')throw Error('console operation must never reset native neural state');},learningBoundary(){},validateProfile(){},status:text=>{state.lastStatus=text;},validateSnapshot(){},rgbaAndRetina(){},localStorage:{getItem:()=>null}};
vm.createContext(state);
for(const [start,end] of [['function keysEqual','function learningKey'],['function ids','function apply'],['function releaseBrain','function agentAllowedMask'],['function agentAllowedMask','function rgbaAndRetina'],['function connectBrain','window.labConfigured='],['window.labPause=function','$(\'play\').onclick='],['function validateConfiguration','function validateSnapshot'],['function restartEpisodeFromRom','function policyPackage']])vm.runInContext(source.slice(source.indexOf(start),source.indexOf(end,source.indexOf(start))),state);
state.requestedConfiguration=state.configuration();state.learner.weights[0][0]=5;
const weights=JSON.stringify(state.learner.weights),config=JSON.stringify(state.requestedConfiguration);
const resetLine=source.split('\n').find(x=>x.startsWith("$('resetNes').onclick="));vm.runInContext(resetLine,state);state.$('resetNes').onclick();
assert.equal(state.frame,5);assert.equal(state.connected,false);assert.deepEqual(calls,['stop']);assert.equal(JSON.stringify(state.learner.weights),weights);assert.equal(JSON.stringify(state.requestedConfiguration),config);
state.connectBrain();assert.equal(state.connected,true,state.lastStatus);assert.deepEqual(calls,['stop','resume']);assert.equal(nativeState.tick,12345);assert.equal(nativeState.fdbRevision,9);
const snap={hash:'own',system:'nes',frame:5,state:core.toJSON()};state.localStorage.getItem=()=>JSON.stringify(snap);
const loadLine=source.split('\n').find(x=>x.startsWith("$('loadState').onclick="));vm.runInContext(loadLine,state);state.$('loadState').onclick();state.connectBrain();assert.equal(calls.filter(x=>x==='configure').length,0);assert.equal(JSON.stringify(state.learner.weights),weights);
const java=fs.readFileSync('app/src/main/java/org/node/flyconsole/NesLabActivity.java','utf8');const accept=java.slice(java.indexOf('@JavascriptInterface public void acceptRom'),java.indexOf('@JavascriptInterface public void sample'));
assert(!/engine\.reset|gpuEngine\.reset|fdbGrowth\.reset/.test(accept),'ROM acceptance must not indirectly reset model');
console.log('PASS: actual NES reset/snapshot with production UI handlers, reconnect without native configure, model weight preservation and no reset on ROM acceptance');
