'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),Tools=require('../app/src/main/assets/lab/game-tools.js');
const source=fs.readFileSync('app/src/main/assets/lab/dual-ui.js','utf8'),html=fs.readFileSync('app/src/main/assets/lab/index.html','utf8'),FLY='flywire-v783',MALE='male-cns-v1.0',sha=id=>(id===FLY?'a':'b').repeat(64);
function fixture(system='sega',store=new Map()){
 const nodes={},calls=[],timers=new Map(),reads=new Map(),ram=new Uint8Array(131072);let timer=0,session=0,lastConfig;
 const node=id=>nodes[id]||(nodes[id]={value:'',textContent:'',checked:false,disabled:false,hidden:false,innerHTML:''});
 for(const [id,value]of Object.entries({actionMasks:'0,1,2,64,128',maxHz:'150',thresholdHz:'30',windowMs:'20',gain:'1',dualManualPort:'1'}))node(id).value=value;
 node('layerAutosave').checked=true;
 const mem=new Proxy({}, {get(_,k){if(/^\d+$/.test(String(k)))reads.set(Number(k),(reads.get(Number(k))||0)+1);return ram[Number(k)];}});
 const state={$:node,window:{},ready:true,loaded:true,romLoading:false,configurationApplied:true,labPlatform:system,romHash:'c'.repeat(64),ramLimit:system==='nes'||system==='gb'?2048:system==='snes'?131072:65536,nes:{cpu:{mem},twoPlayerSupported:system!=='gb'},playing:false,performance:{now:()=>0},FlyGameTools:Tools,
  localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},persistPolicy:()=>calls.push({op:'persist'}),status:(text,error)=>calls.push({op:'status',text,error}),controlsEnabled:value=>calls.push({op:'controls',value}),openGame:()=>calls.push({op:'open'}),updateGmodeHud(){},updateButtons:()=>calls.push({op:'route'}),releasePorts:()=>calls.push({op:'release'}),agentAllowedMask:()=>system==='sega'||system==='snes'?2039:243,
  setTimeout:(fn,ms)=>{const id=++timer;timers.set(id,{fn,ms});return id;},clearTimeout:id=>timers.delete(id)};
 const meta=(a,i)=>({id:a.id,modelId:a.modelId,graphSha256:sha(a.modelId),layerId:'layer-'+i,fdbState:{edges:[],deltas:[],learningState:{automatic:0}},revision:0,memoryBytes:4096,saved:true});
 state.window.FlyBridge={dualConfigure(text){const q=JSON.parse(text);lastConfig=q;session++;state.window.labDualReady({epoch:q.epoch,token:q.token,sessionId:'s-'+session,singleResetRequired:true,agents:q.agents.map(meta),estimatedBytes:1000000,heapAvailableBytes:2000000});},dualSample(){},dualBoundary(text){const q=JSON.parse(text);state.window.labDualBoundary({epoch:q.epoch,token:q.token,sessionId:q.sessionId,agents:lastConfig?.agents.map(meta)});},dualExit(text){const q=JSON.parse(text);state.window.labDualExited({epoch:q.epoch,token:q.token,sessionId:q.sessionId,ok:true});},resume(){},stop(){}};
 state.nativeCall=(op,...args)=>{calls.push({op,payload:op.startsWith('dual')?JSON.parse(args[0]):args[0]});state.window.FlyBridge[op](...args);};
 state.window.labPause=()=>{calls.push({op:'pause'});state.playing=false;if(state.window.dualAgents?.active())state.window.dualAgents.pause('pause');};
 state.window.fdbAgent={drain:async()=>{},error:()=>null};state.window.layerExperience={activeId:()=>null,autosave:async()=>false};
 vm.createContext(state);vm.runInContext(source,state);const api=state.window.dualAgents,last=op=>calls.findLast(c=>c.op===op)?.payload;
 const result=(extra={})=>{const q=last('dualSample');state.window.labDualResult({epoch:q.epoch,token:q.token,sessionId:q.sessionId,wallMs:20,agents:lastConfig.agents.map((a,i)=>({...meta(a,i),decision:{id:q.token+'-'+a.id,mask:i?64:128,probability:.5}})),...extra});};
 const frames=(n=6,overrides=[false,false],actual=Array.from(api.route()))=>{for(let i=0;i<n;i++)api.frame({masks:actual,dt:1/60,overrides});};
 const sample=(now,retina=new Array(16).fill(.25),force=true)=>api.sample({retina,frame:Math.round(now*60/1000),now,force});
 return{node,state,calls,timers,reads,ram,api,last,result,frames,sample,meta,store,prefKey:()=> 'fly-dual-preferences-'+system+'-'+state.romHash};
}
const turn=()=>new Promise(setImmediate);
(async()=>{
 assert(html.includes('src="dual-ui.js"')&&html.includes('href="dual-ui.css"'));assert(html.includes('доказательство индивидуального вклада'));assert(source.includes("$('dualCards').innerHTML=card(0)+card(1)"),'both real port cards are mounted');
 let f=fixture();assert(!f.api.active());assert.deepEqual(Array.from(f.api.route()),[0,0]);await f.api.configure();assert(f.api.active()&&f.api.running()&&f.state.playing);let q=f.last('dualConfigure');assert.equal(q.agents[0].modelId,FLY);assert.equal(q.agents[1].modelId,MALE);assert(q.agents.every(a=>a.config.backend==='cpu'));assert(!('inputs'in q.agents[0].config));assert.equal(f.state.configurationApplied,false);assert.equal(f.node('backend').value,'cpu');assert(f.store.has(f.prefKey()),'preferences saved only after real ready');
 f.sample(0);assert(!f.last('dualSample').agents[0].outcome);f.result();assert.deepEqual(Array.from(f.api.route()),[128,64]);f.frames();f.node('dual1Plus').onclick();f.node('dual2Minus').onclick();f.sample(100);q=f.last('dualSample');assert.equal(q.agents[0].outcome.reward,1);assert.equal(q.agents[1].outcome.reward,-1);assert.equal(q.agents[0].outcome.frames,6);assert.notEqual(q.agents[0].outcome.id,q.agents[1].outcome.id);
 const count=f.calls.filter(c=>c.op==='dualSample').length;f.sample(110);assert.equal(f.calls.filter(c=>c.op==='dualSample').length,count);f.result();f.frames(6,[true,false]);f.sample(200);q=f.last('dualSample');assert.equal(q.agents[0].outcome.valid,false);assert.equal(q.agents[1].outcome.valid,true,'credit is only excluded for the intervened port');f.result();
 f.api.pause();await f.api.drain();assert(f.api.active()&&!f.api.running());assert(await f.api.resume());assert.equal(f.calls.filter(c=>c.op==='dualConfigure').length,1,'resume preserves live brains');const resumes=f.calls.filter(c=>c.op==='resume').length;await f.api.boundary('freeze');assert(f.api.running());assert.equal(f.calls.filter(c=>c.op==='resume').length,resumes+1,'live boundary clears native cancellation');f.api.pause();await f.api.drain();f.node('dual2Seed').value='9';assert.equal(await f.api.resume(),false,'dirty settings require explicit apply');
 f=fixture();for(const i of [1,2]){f.node('dual'+i+'RewardMode').value='ram';f.node('dual'+i+'Scale').value=i===1?'1':'-.5';}f.node('dual2Address').value='1';await f.api.configure();f.ram[0]=10;f.ram[1]=20;f.sample(0);f.ram[0]=100;f.ram[1]=200;f.result();f.ram[0]=102;f.ram[1]=210;f.frames();f.reads.clear();f.sample(100);q=f.last('dualSample');assert.equal(q.agents[0].outcome.reward,2);assert.equal(q.agents[1].outcome.reward,-5,'backend-tail RAM changes are excluded');assert.equal(f.reads.get(0),1);assert.equal(f.reads.get(1),1,'one shared cut reads each RAM address once');f.ram[0]=150;assert.equal(q.agents[0].outcome.reward,2);f.result();f.frames();f.node('freeze').checked=true;f.sample(200);assert(f.last('dualSample').agents.every(a=>a.frozen));f.result();f.frames();f.sample(300,new Array(16).fill(.8));assert(f.last('dualSample').retina.every(v=>v===.25));
 f=fixture();f.node('dualTeam').checked=true;f.node('dual1RewardMode').value='ram';f.node('dual1Scale').value='1';f.node('dual2Address').value='1';await f.api.configure();q=f.last('dualConfigure');assert.deepEqual(q.agents[1].profile,q.agents[0].profile,'checkpoint stores effective shared objective');f.ram[0]=5;f.ram[1]=200;f.sample(0);f.result();f.ram[0]=7;f.ram[1]=1;f.frames();f.node('dualTeamPlus').onclick();f.reads.clear();f.sample(100);q=f.last('dualSample');assert.equal(q.agents[0].outcome.reward,3);assert.equal(q.agents[1].outcome.reward,3);assert.equal(f.reads.get(0),1);assert(!f.reads.has(1));assert(f.node('dual2Address').disabled&&f.node('dual1Plus').disabled);
 f=fixture();f.node('dual2Mode').value='eval';await f.api.configure();f.sample(0);q=f.last('dualSample');assert.equal(q.agents[1].mode,'eval');f.result();f.frames();f.sample(100);q=f.last('dualSample');f.state.window.labDualResult({epoch:q.epoch-1,token:q.token,sessionId:q.sessionId,agents:[]});assert.deepEqual(Array.from(f.api.route()),[128,64]);f.api.pause();f.result();assert.deepEqual(Array.from(f.api.route()),[0,0],'late result cannot resume paused actors');await f.api.drain();await f.api.exit();assert(!f.api.active());assert(f.calls.some(c=>c.op==='dualExit')&&f.calls.some(c=>c.op==='release'));
 f=fixture();await f.api.configure();f.sample(0);f.result();const samples=f.calls.filter(c=>c.op==='dualSample').length;f.sample(0,new Array(16).fill(.4),true);assert.equal(f.calls.filter(c=>c.op==='dualSample').length,samples,'same actual frame is never reused');f.state.romHash='d'.repeat(64);f.sample(100);assert(!f.api.running());assert.deepEqual(Array.from(f.api.route()),[0,0]);
 f=fixture('gb');await f.api.configure();assert(!f.calls.some(c=>c.op==='dualConfigure'));assert(!f.api.active());assert(f.node('dualStatus').textContent.includes('два игровых порта'));
 f=fixture();delete f.state.window.FlyBridge.dualSample;await f.api.configure();assert(!f.calls.some(c=>c.op==='pause'),'unsupported bridge does not mutate current mode');
 f=fixture();await f.api.configure();f.sample(0);Array.from(f.timers.values()).find(t=>t.ms===30000).fn();assert(!f.api.running());assert.deepEqual(Array.from(f.api.route()),[0,0]);
 f=fixture();await f.api.configure();f.state.window.FlyBridge.dualExit=text=>{const q=JSON.parse(text);f.state.window.labDualExited({epoch:q.epoch,token:q.token,error:'Not durable',ok:false});};assert.equal(await f.api.exit(),false);assert(f.api.active());assert.deepEqual(Array.from(f.api.route()),[0,0]);
 f=fixture();let loading;f.state.window.FlyBridge.dualConfigure=text=>{loading=JSON.parse(text);};const starting=f.api.configure();await turn();f.api.pause('loading');assert(!f.calls.some(c=>c.op==='dualBoundary'),'no boundary before known session');f.state.window.labDualReady({epoch:loading.epoch,token:loading.token,sessionId:'delayed',agents:loading.agents.map(f.meta)});await starting;assert(!f.api.running()&&!f.state.playing,'pause cancels late auto-start');
 // Restart restores choices/objective and stays inactive. New ROM gets safe defaults.
 f=fixture();f.node('dual1Model').value=MALE;f.node('dual2Seed').value='73';f.node('dual2Mode').value='eval';f.node('dual2RewardMode').value='ram';f.node('dual2Address').value='42';f.node('dual2Width').value='2';f.node('dual2Endian').value='big';f.node('dual2Scale').value='-.7';f.node('dualManualPort').value='2';await f.api.configure();const reopened=fixture('sega',f.store);assert(!reopened.api.active()&&!reopened.state.playing);assert(!reopened.calls.some(c=>c.op==='dualConfigure'));assert.equal(reopened.node('dual1Model').value,MALE);assert.equal(reopened.node('dual2Seed').value,'73');assert.equal(reopened.node('dual2Mode').value,'eval');assert.equal(reopened.node('dual2Address').value,'42');assert.equal(reopened.node('dual2Endian').value,'big');assert.equal(reopened.api.manualPort(),2);reopened.state.romHash='e'.repeat(64);reopened.api.refresh();assert.equal(reopened.node('dual1Model').value,FLY);assert.equal(reopened.node('dual2RewardMode').value,'manual');
 const corrupted=new Map([[f.prefKey(),'{bad json']]);f=fixture('sega',corrupted);await f.api.configure();assert(!f.calls.some(c=>c.op==='dualConfigure'),'corruption never silently chooses a different objective');f.node('dualResetPreferences').onclick();await f.api.configure();assert(f.api.running(),'explicit preference reset recovers without deleting weights');
 f=fixture();f.state.localStorage.setItem=()=>{throw Error('Quota');};await f.api.configure();assert(f.api.active()&&!f.api.running()&&!f.state.playing,'preference durability failure prevents game actuation');assert(f.node('dualStatus').textContent.includes('сохранить настройки'));assert.equal(await f.api.resume(),false);
 console.log('PASS: production dual UI routing/credit, shared RAM cuts/tail exclusion, CPU/freeze/Eval/team, stale/context/frame guards, pause/loading/exit durability and per-ROM preferences without auto-start');
})().catch(e=>{console.error(e);process.exitCode=1;});
