package org.node.flyconsole;

import java.io.*;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.atomic.AtomicBoolean;
import org.json.*;

/** Production scoped CPU/FDB contexts and durable pair checks; no substitute engine. */
public final class DualAgentCheck {
 private static final String FLY="flywire-v783",MALE="male-cns-v1.0",FIXTURE="mechanism-fixture",ROM=String.format("%064d",17);
 private static final String FLY_SHA="c8b50d82ff3641ddd148723222e3052b209c2662ce587def294553404d3cc2c5",MALE_SHA="90d9baae7627a521b08d5112eeb27057994b213bb2ecbc00aae1fb1c52e1cb56";
 private static final long[] MALE_IN={11139,117405,140141,155183,167031,176950,186714,195948,206934,221057,235427,260823,340551,500151,552475,1035284341};
 private static final long[] MALE_OUT={164190,801304,802500,803891,805881,807873,812872,818553,830514,905928,1050032839,1059707690};
 private static void require(boolean value,String message){if(!value)throw new AssertionError(message);}
 private interface RejectedOperation {void run()throws Exception;}
 private static void rejects(RejectedOperation operation,String message)throws Exception {boolean rejected=false;try{operation.run();}catch(IllegalArgumentException expected){rejected=true;}require(rejected,message);}
 private static void requestGuardCheck()throws Exception {
  DualRequestGuard guard=new DualRequestGuard("dual-1");require(guard.fresh(2)&&!guard.fresh("dual-1"),"configure token establishes numeric/string serial floor");guard.sample("dual-2",10);guard.boundary("dual-3");
  rejects(()->guard.sample("dual-2",10),"old observation after boundary rejected");require(guard.fresh("dual-4"),"stale observation does not consume next serial");guard.sample("dual-4",0);
  rejects(()->guard.sample(4,1),"duplicate sample rejected after legitimate frame rewind");rejects(()->guard.sample(5,0),"fresh token cannot repeat frame without boundary");guard.sample(5,1);
  rejects(()->guard.boundary("dual-4"),"old boundary cannot reset accepted frame");rejects(()->guard.sample("dual-6",0),"rejected old boundary leaves frame fence intact");guard.sample("dual-6",2);guard.boundary(7);guard.sample(8,0);
  for(Object bad:new Object[]{null,"", "dual-", "dual--1", "dual-1.5", "9", "dual-9007199254740992", "dual-00000000000000001", -1,1.5,Double.NaN,Double.POSITIVE_INFINITY,9007199254740992L,new Object()}){
   rejects(()->new DualRequestGuard(bad),"malformed configure token rejected");rejects(()->guard.sample(bad,1),"malformed sample token rejected");rejects(()->guard.boundary(bad),"malformed boundary token rejected");require(guard.fresh(9),"malformed request preserves accepted serial");
  }
  rejects(()->guard.sample(9,-1),"negative frame rejected");rejects(()->guard.sample(9,9007199254740992L),"frame beyond JavaScript safe integer rejected");guard.sample("dual-9",1);
  DualRequestGuard numeric=new DualRequestGuard(0);numeric.boundary("dual-1");numeric.sample(2,0);require(!numeric.fresh("dual-2")&&numeric.fresh(3),"numeric configure and mixed token forms share one serial order");
  long max=9007199254740991L;require(DualRequestGuard.serial(max)==max&&DualRequestGuard.serial("dual-"+max)==max,"maximum JavaScript-safe token retained exactly");DualRequestGuard limit=new DualRequestGuard(0);limit.sample("dual-"+max,max);require(!limit.fresh(max),"maximum safe frame/token accepted once");
 }
 private static Graph read(String path)throws Exception{try(InputStream in=new FileInputStream(path)){return Graph.read(in,1_000_000_000L);}}
 private static Graph fixture(){long[] ids=new long[30];for(int i=0;i<ids.length;i++)ids[i]=i+1;return new Graph(ids,new int[31],new int[0],new float[0]);}
 private static Experiment ports(Graph graph,String model){
  if(model.equals(MALE)){int[] input=new int[16],output=new int[12];for(int i=0;i<16;i++)input[i]=Arrays.binarySearch(graph.ids,MALE_IN[i]);for(int i=0;i<12;i++)output[i]=Arrays.binarySearch(graph.ids,MALE_OUT[i]);return new Experiment(input,output);}
  return Experiment.automatic(graph,12);
 }
 private static boolean base(Graph graph,int source,int target){for(int i=graph.offsets[source];i<graph.offsets[source+1];i++)if(graph.targets[i]==target)return true;return false;}
 private static JSONObject descriptor(Graph graph,Experiment ports,long seed,int window)throws Exception{
  JSONArray edges=new JSONArray();for(int input:ports.inputs)for(int button:new int[]{0,6,7}){int target=ports.outputs[button];if(!base(graph,input,target))edges.put(new JSONObject().put("source",Long.toString(graph.ids[input])).put("target",Long.toString(graph.ids[target])).put("weight",4));}
  return new JSONObject().put("seed",seed).put("config",new JSONObject().put("backend","cpu").put("mode","closed").put("windowMs",window).put("maxHz",500).put("thresholdHz",30).put("gain",1)
   .put("fdb",new JSONObject().put("deltas",new JSONArray()).put("edges",edges).put("learning",new JSONObject().put("enabled",true).put("rate",.1).put("maxEdges",128).put("maxWeight",127))));
 }
 private static DualAgentContext context(String id,String model,Graph graph,Experiment defaults,JSONObject descriptor,JSONObject checkpoint,String layerId)throws Exception{return DualAgentContext.create(id,model,graph,defaults,new JSONObject(descriptor.toString()).put("id",id).put("modelId",model),checkpoint,layerId);}
 private static DualAgentContext actor(String id,String model,Graph graph,JSONObject config)throws Exception{return context(id,model,graph,ports(graph,model),config,null,UUID.randomUUID().toString());}
 private static String outputs(JSONObject sample)throws Exception{return sample.getJSONArray(sample.has("outputsHz")?"outputsHz":"outputs").toString();}
 private static JSONObject request(String slot,String mode,int[] actions,JSONObject outcome)throws Exception{
  JSONObject result=new JSONObject().put("id",slot).put("mode",mode).put("epsilon",.1).put("allowedMask",4095).put("actions",new JSONArray(actions)).put("frozen",false);if(outcome!=null)result.put("outcome",outcome);return result;
 }
 private static JSONObject outcome(JSONObject sample,double reward)throws Exception{JSONObject decision=sample.getJSONObject("decision");return new JSONObject().put("id",decision.getString("id")).put("mask",decision.getInt("mask")).put("frames",6).put("gameSeconds",.1).put("reward",reward).put("valid",true);}
 private static String hash(String text)throws Exception{byte[] digest=MessageDigest.getInstance("SHA-256").digest(text.getBytes(java.nio.charset.StandardCharsets.UTF_8));StringBuilder result=new StringBuilder();for(byte b:digest)result.append(String.format(Locale.ROOT,"%02x",b&255));return result.toString();}
 private static String weightsKey(GraphDelta layer){StringBuilder result=new StringBuilder();for(String kind:new String[]{"d","e"}){List<GraphDelta.Edge> edges=kind.equals("d")?layer.deltas():layer.edges();edges.sort(Comparator.comparingInt((GraphDelta.Edge e)->e.source).thenComparingInt(e->e.target));for(GraphDelta.Edge e:edges)result.append(kind).append(':').append(e.source).append(':').append(e.target).append(':').append(Float.floatToIntBits(e.weight)).append(';');}return result.toString();}
 private static JSONObject summary(DualAgentContext actor)throws Exception{return new JSONObject().put("id",actor.id).put("model",actor.modelId).put("graphSha",actor.graph.fingerprint()).put("neurons",actor.graph.ids.length).put("baseEdges",actor.graph.targets.length)
  .put("acquiredEdges",actor.layer.growthCount()).put("automatic",actor.learning.automatic()).put("rng",actor.learning.rng()).put("rejected",actor.learning.rejected()).put("weightsSha",hash(weightsKey(actor.layer))).put("learningSha",hash(actor.fdbState().getJSONObject("learningState").toString()))
  .put("layerBytesEstimate",actor.layer.memoryBytes()+actor.learning.memoryBytes()).put("windowMs",actor.experiment.windowMs);}
 private static JSONObject graphCheck(Graph graph,String model)throws Exception{
  long started=System.nanoTime();String fingerprint=graph.fingerprint();JSONObject config=descriptor(graph,ports(graph,model),11,5);DualAgentContext a=actor("p1",model,graph,config),b=actor("p2",model,graph,config),reference=actor("p1",model,graph,config);
  require(a.graph==b.graph&&a.engine!=b.engine&&a.layer!=b.layer&&a.learning!=b.learning,"shared W0 requires independent Engine/FDB/RNG");double[] retina=new double[16];Arrays.fill(retina,1);double engineMs=0;
  JSONObject da=a.sample(request("p1","train",new int[]{0,1},null),retina,"p1:start",new AtomicBoolean()),ref=reference.sample(request("p1","train",new int[]{0,1},null),retina,"reference:start",new AtomicBoolean());engineMs+=da.getDouble("wallMs");
  require(outputs(da).equals(outputs(ref))&&da.getLong("spikes")==ref.getLong("spikes"),"same graph/seed reproducible CPU state");
  JSONObject db=b.sample(request("p2","train",new int[]{0,1},null),retina,"p2:start",new AtomicBoolean());engineMs+=db.getDouble("wallMs");require(outputs(da).equals(outputs(db))&&da.getLong("spikes")==db.getLong("spikes"),"advancing P1 leaves P2 LIF phase untouched");
  String bBefore=b.fdbState().toString(),aWeights=weightsKey(a.layer),bWeights=weightsKey(b.layer);
  for(int i=0;i<8;i++){
   double reward=da.getJSONObject("decision").getInt("mask")==1?1:-1;da=a.sample(request("p1","train",new int[]{0,1},outcome(da,reward)),retina,"p1:train:"+i,new AtomicBoolean());engineMs+=da.getDouble("wallMs");require(bBefore.equals(b.fdbState().toString()),"P1 reward cannot mutate P2 topology/traces/RNG");String aBefore=a.fdbState().toString();
   double opposing=db.getJSONObject("decision").getInt("mask")==1?-1:1;db=b.sample(request("p2","train",new int[]{0,1},outcome(db,opposing)),retina,"p2:train:"+i,new AtomicBoolean());engineMs+=db.getDouble("wallMs");require(aBefore.equals(a.fdbState().toString()),"P2 reward cannot mutate P1 topology/traces/RNG");bBefore=b.fdbState().toString();
  }
  require(a.learning.automatic()==8&&b.learning.automatic()==8,"separate completed outcome counters");require(!aWeights.equals(weightsKey(a.layer))&&!bWeights.equals(weightsKey(b.layer)),"actual CPU activity updates both actors' weights");require(!weightsKey(a.layer).equals(weightsKey(b.layer)),"opposite rewards cause different acquired weights");
  for(DualAgentContext owner:new DualAgentContext[]{a,b}){
   String before=owner.fdbState().toString();long rng=owner.learning.rng();owner.sample(request(owner.id,"eval",new int[]{0,1},null),retina,owner.id+":eval",new AtomicBoolean());require(before.equals(owner.fdbState().toString())&&rng==owner.learning.rng(),"eval freezes weights/counters/eligibility/RNG");
   owner.sample(request(owner.id,"train",new int[]{0,1},null).put("frozen",true),retina,owner.id+":frozen",new AtomicBoolean());require(before.equals(owner.fdbState().toString()),"frozen training is immutable");
   for(JSONObject invalid:new JSONObject[]{request(owner.id,"train",new int[]{1,2},null).put("allowedMask",0),request(owner.id,"train",new int[]{1,1},null),request(owner.id,"train",new int[]{0,1},null).put("outcome",new JSONObject().put("id","bad").put("mask",0).put("frames",0).put("gameSeconds",.1).put("reward",1).put("valid",true))}){boolean rejected=false;try{owner.validateRequest(invalid);}catch(Exception expected){rejected=true;}require(rejected&&before.equals(owner.fdbState().toString()),"invalid allowed actions/outcome rejected before mutation");}
  }
  String stableA=a.fdbState().toString(),stableB=b.fdbState().toString();b.sample(request("p2","train",new int[]{0,1},outcome(da,1)),retina,"p2:foreign",new AtomicBoolean());require(stableA.equals(a.fdbState().toString())&&b.learning.rejected()==1,"foreign P1 decision cannot earn P2 credit");require(new JSONObject(stableB).getJSONArray("edges").toString().equals(b.fdbState().getJSONArray("edges").toString()),"foreign outcome cannot change receiver topology");
  a.boundary();b.boundary();a.engine.reset(11);b.engine.reset(11);JSONObject packet=a.layerSet("sega",ROM,1);DualAgentContext restored=context("p1",model,graph,ports(graph,model),config,new JSONObject(packet.toString()),packet.getString("id"));require(a.fdbState().toString().equals(restored.fdbState().toString()),"complete learned checkpoint after temporal boundary");String bAtResume=b.fdbState().toString();JSONObject old=null,next=null;
  for(int i=0;i<4;i++){
   old=a.sample(request("p1","train",new int[]{0,1},old==null?null:outcome(old,old.getJSONObject("decision").getInt("mask")==1?1:-1)),retina,"continued:"+i,new AtomicBoolean());next=restored.sample(request("p1","train",new int[]{0,1},next==null?null:outcome(next,next.getJSONObject("decision").getInt("mask")==1?1:-1)),retina,"continued:"+i,new AtomicBoolean());
   require(old.getJSONObject("decision").getInt("mask")==next.getJSONObject("decision").getInt("mask")&&outputs(old).equals(outputs(next)),"restored RNG/reset dynamics reproduce actions");require(a.fdbState().toString().equals(restored.fdbState().toString())&&bAtResume.equals(b.fdbState().toString()),"continued P1 learning equals restored actor and preserves P2");
  }
  boolean wrongSlot=false;try{context("p2",model,graph,ports(graph,model),config,packet,UUID.randomUUID().toString());}catch(Exception expected){wrongSlot=true;}require(wrongSlot,"cross-slot checkpoint rejected");boolean wrongModel=false;try{context("p1","different-"+model,graph,ports(graph,model),config,packet,UUID.randomUUID().toString());}catch(Exception expected){wrongModel=true;}require(wrongModel,"cross-model checkpoint rejected even with identical graph arrays");boolean gpu=false;try{actor("p1",model,graph,new JSONObject(config.toString()).put("config",new JSONObject(config.getJSONObject("config").toString()).put("backend","gpu")));}catch(Exception expected){gpu=true;}require(gpu,"dual refuses unsupported GPU ownership");
  require(fingerprint.equals(new Graph(graph.ids,graph.offsets,graph.targets,graph.weights).fingerprint()),"fresh digest confirms W0 arrays immutable");long graphBytes=12L*graph.ids.length+8L*graph.targets.length+4;
  return new JSONObject().put("model",model).put("neurons",graph.ids.length).put("baseEdges",graph.targets.length).put("graphSha",fingerprint).put("immutableGraphBytes",graphBytes).put("twoEnginesBytesEstimate",208L*graph.ids.length).put("pairGraphAndEnginesBytesEstimate",graphBytes+208L*graph.ids.length).put("measuredEngineMs",engineMs).put("checkWallMs",(System.nanoTime()-started)/1e6).put("p1",summary(a)).put("p2",summary(b));
 }
 private static void cleanup(File root)throws Exception{File layers=new File(root,"layer-sets");File[] files=layers.listFiles();if(files!=null)for(File file:files)require(file.delete(),"test file cleanup");if(layers.exists())require(layers.delete(),"test folder cleanup");File index=new File(root,"dual-agent-bindings.json");if(index.exists())require(index.delete(),"test index cleanup");require(root.delete(),"test root cleanup");}
 private static void storeCheck()throws Exception{
  Graph graph=fixture();JSONObject config=descriptor(graph,ports(graph,FIXTURE),7,5);File root=Files.createTempDirectory("fly-dual-check-").toFile();try{
   DualLayerStore store=new DualLayerStore(root);DualLayerStore.Binding[] bindings={store.prepare("sega",ROM,graph.fingerprint(),"p1",FIXTURE,false),store.prepare("sega",ROM,graph.fingerprint(),"p2",FIXTURE,false)};DualAgentContext[] owners=new DualAgentContext[2];for(int i=0;i<2;i++)owners[i]=context("p"+(i+1),FIXTURE,graph,ports(graph,FIXTURE),config,null,bindings[i].id);store.commitPair(bindings,owners,"sega",ROM);require(!owners[0].layerId.equals(owners[1].layerId),"separate persistent layer UUIDs");
   LayerSetStore layers=new LayerSetStore(new File(root,"layer-sets"));String p2Before=layers.get(owners[1].layerId).toString();double[] retina=new double[16];Arrays.fill(retina,1);JSONObject decision=owners[0].sample(request("p1","train",new int[]{0,1},null),retina,"store:first",new AtomicBoolean());owners[0].sample(request("p1","train",new int[]{0,1},outcome(decision,decision.getJSONObject("decision").getInt("mask")==1?1:-1)),retina,"store:second",new AtomicBoolean());store.save(owners[0],"sega",ROM,1);require(p2Before.equals(layers.get(owners[1].layerId).toString()),"P1 native save preserves P2 file");DualLayerStore reopen=new DualLayerStore(root);
   for(int i=0;i<2;i++){DualLayerStore.Binding binding=reopen.prepare("sega",ROM,graph.fingerprint(),"p"+(i+1),FIXTURE,true);require(binding.id.equals(owners[i].layerId)&&!binding.fresh,"binding survives reopen");require(binding.checkpoint.getJSONObject("configuration").getJSONObject("fdb").getJSONArray("edges").toString().equals(owners[i].fdbState().getJSONArray("edges").toString()),"Wexo survives file reopen");}
   boolean wrongModel=false;try{reopen.prepare("sega",ROM,graph.fingerprint(),"p1","other-mechanism-fixture",true);}catch(Exception expected){wrongModel=true;}require(wrongModel,"model identity mismatch cannot steal checkpoint");String indexBefore=new String(Files.readAllBytes(new File(root,"dual-agent-bindings.json").toPath()),java.nio.charset.StandardCharsets.UTF_8);int fileCount=layers.list().length();boolean wrongBinding=false;
   try{store.commitPair(new DualLayerStore.Binding[]{bindings[1],bindings[0]},owners,"sega",ROM);}catch(Exception expected){wrongBinding=true;}require(wrongBinding&&indexBefore.equals(new String(Files.readAllBytes(new File(root,"dual-agent-bindings.json").toPath()),java.nio.charset.StandardCharsets.UTF_8)),"wrong binding/context ownership rejected before index rewrite");
   String invalidName="invalid-checkpoint-name-".repeat(9);DualLayerStore.Binding[] proposedBindings={store.prepare("sega",ROM,graph.fingerprint(),"p1",FIXTURE,false),store.prepare("sega",ROM,graph.fingerprint(),"p2",invalidName,false)};DualAgentContext[] proposed={context("p1",FIXTURE,graph,ports(graph,FIXTURE),config,null,proposedBindings[0].id),context("p2",invalidName,graph,ports(graph,FIXTURE),config,null,proposedBindings[1].id)};boolean failed=false;
   try{store.commitPair(proposedBindings,proposed,"sega",ROM);}catch(Exception expected){failed=true;}require(failed&&layers.list().length()==fileCount&&indexBefore.equals(new String(Files.readAllBytes(new File(root,"dual-agent-bindings.json").toPath()),java.nio.charset.StandardCharsets.UTF_8)),"second staged checkpoint failure rolls back fresh files and preserves installed pair");
  }finally{cleanup(root);}
 }
 private static void bridge(Map<String,Graph> graphs)throws Exception{
  File files=Files.createTempDirectory("fly-dual-game-").toFile();DualLayerStore store=new DualLayerStore(files);DualAgentContext[] owners=new DualAgentContext[2];long counter=0;String system="sega",rom=ROM;long[] created={1,1};
  try(BufferedReader input=new BufferedReader(new InputStreamReader(System.in))){String line;while((line=input.readLine())!=null){JSONObject q=new JSONObject(line),result=new JSONObject();String op=q.getString("op");
   if(op.equals("init")){system=q.getString("system");if(system.equals("gb"))throw new IllegalArgumentException("GB has no independent P2");rom=q.getString("romHash");String[] models={q.optString("p1Model",FLY),q.optString("p2Model",MALE)};DualAgentContext[] next=new DualAgentContext[2];DualLayerStore.Binding[] bindings=new DualLayerStore.Binding[2];
    for(int i=0;i<2;i++){Graph graph=graphs.get(models[i]);if(graph==null)throw new IllegalArgumentException("model");bindings[i]=store.prepare(system,rom,graph.fingerprint(),"p"+(i+1),models[i],false);next[i]=context("p"+(i+1),models[i],graph,ports(graph,models[i]),descriptor(graph,ports(graph,models[i]),i==0?11:23,10),null,bindings[i].id);created[i]=bindings[i].createdAt;}
    store.commitPair(bindings,next,system,rom);owners=next;long bytes=owners[0].graph.memoryBytes()+owners[1].graph.memoryBytes();if(owners[0].graph==owners[1].graph)bytes-=12L*owners[0].graph.ids.length+8L*owners[0].graph.targets.length+4;result.put("graphShared",owners[0].graph==owners[1].graph).put("fullGraphs",true).put("pairGraphAndEnginesBytesEstimate",bytes);
   }else if(op.equals("sample")){JSONArray raw=q.getJSONArray("retina"),requests=q.getJSONArray("agents");require(raw.length()==16&&requests.length()==2,"pair sample shape");double[] retina=new double[16];for(int i=0;i<16;i++){retina[i]=raw.getDouble(i);require(Double.isFinite(retina[i])&&retina[i]>=0&&retina[i]<=1,"valid observation");}for(int i=0;i<2;i++)owners[i].validateRequest(requests.getJSONObject(i));JSONArray responses=new JSONArray();for(int i=0;i<2;i++){responses.put(owners[i].sample(requests.getJSONObject(i),retina,"bridge:"+owners[i].id+":"+counter,new AtomicBoolean()));store.save(owners[i],system,rom,created[i]);}counter++;result.put("agents",responses);
   }else if(op.equals("checkpoint")){int i=q.getString("id").equals("p1")?0:1;DualAgentContext old=owners[i];old.boundary();store.save(old,system,rom,created[i]);DualLayerStore.Binding binding=new DualLayerStore(files).prepare(system,rom,old.graph.fingerprint(),old.id,old.modelId,true);owners[i]=context(old.id,old.modelId,old.graph,ports(old.graph,old.modelId),new JSONObject().put("seed",old.experiment.seed).put("config",old.configuration),binding.checkpoint,binding.id);}
   else if(op.equals("boundary")){for(DualAgentContext owner:owners)owner.boundary();}else if(!op.equals("state"))throw new IllegalArgumentException(op);JSONArray states=new JSONArray();for(DualAgentContext owner:owners)states.put(summary(owner));result.put("states",states);System.out.println(result);
  }}finally{cleanup(files);}
 }
 public static void main(String[] args)throws Exception{
  boolean useBridge=args.length>0&&args[0].equals("--bridge");int start=useBridge?1:0;boolean full=args.length-start==2;require(full||(!useBridge&&args.length==0),"Expected FlyWire and Male CNS graph paths; bridge requires both real models");Map<String,Graph> graphs=new LinkedHashMap<>();
  if(full){Graph fly=read(args[start]),male=read(args[start+1]);require(fly.ids.length==138639&&fly.targets.length==15091983&&fly.fingerprint().equals(FLY_SHA),"full pinned FlyWire universe");require(male.ids.length==165122&&male.targets.length==25563197&&male.fingerprint().equals(MALE_SHA),"full pinned Male CNS universe");graphs.put(FLY,fly);graphs.put(MALE,male);}else graphs.put(FIXTURE,fixture());
  if(useBridge){bridge(graphs);return;}requestGuardCheck();JSONArray rows=new JSONArray();for(Map.Entry<String,Graph> graph:graphs.entrySet())rows.put(graphCheck(graph.getValue(),graph.getKey()));storeCheck();System.out.println("PASS: production dual contexts; request serial/frame boundary fencing, shared W0, isolated CPU/FDB/reward/RNG, frozen evaluation, continued checkpoint, strict identity and durable pair rollback; "+(full?"full official graphs":"explicit 30-neuron mechanism fixture"));
  System.out.println(new JSONObject().put("kind","dual-context-isolation-diagnostics").put("fullGraphs",full).put("limits","Controlled technical I/O/rewards, no commercial-game success or biological equivalence. Checkpoint resumes learned topology with reset LIF dynamics.").put("rows",rows));
 }
}
