'use strict';
// Real console frames and real full graphs through production DualAgentContext.
// Cartridge tasks diagnose routing/credit isolation, not commercial-game intelligence.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),{spawn}=require('node:child_process'),readline=require('node:readline');
const assets=path.resolve(__dirname,'../app/src/main/assets/lab'),cores=process.env.DUAL_CORES||process.env.FDB_CORES||assets,fly=process.env.DUAL_FLY_GRAPH||path.resolve(assets,'../brain.fly'),male=process.env.DUAL_MALE_GRAPH||path.resolve(assets,'../male-cns.fly.gz');
assert(fs.existsSync(fly)&&fs.existsSync(male),'Both real full model assets required; run after bundle_data.py or set DUAL_FLY_GRAPH/DUAL_MALE_GRAPH');
function bridge(){
 assert(process.env.CODE_CLASSPATH,'CODE_CLASSPATH required');const child=spawn(process.env.JAVA||'java',['-Xmx1024m','-cp',process.env.CODE_CLASSPATH,'org.node.flyconsole.DualAgentCheck','--bridge',fly,male],{stdio:['pipe','pipe','inherit']}),pending=[];
 readline.createInterface({input:child.stdout}).on('line',line=>{const next=pending.shift();if(next)try{next.resolve(JSON.parse(line));}catch(error){next.reject(error);}});
 const finished=new Promise(resolve=>child.once('exit',code=>{while(pending.length)pending.shift().reject(Error('dual bridge exited '+code));resolve(code);}));child.on('error',error=>{while(pending.length)pending.shift().reject(error);});
 return {call:q=>new Promise((resolve,reject)=>{pending.push({resolve,reject});child.stdin.write(JSON.stringify(q)+'\n');}),close:async()=>{child.stdin.end();assert.equal(await finished,0,'native diagnostics exit cleanly');}};
}
const request=(id,mode,outcome=null,frozen=false)=>({id,mode,epsilon:.1,allowedMask:4095,actions:id==='p1'?[128,64]:[64,128],frozen,...(outcome?{outcome}: {})});
const checkpointFields=state=>({automatic:state.automatic,rng:state.rng,weightsSha:state.weightsSha,learningSha:state.learningSha,rejected:state.rejected});
const sameLearning=(a,b,message)=>assert.deepEqual(checkpointFields(a),checkpointFields(b),message),sameAcquired=(a,b,message)=>assert.deepEqual({automatic:a.automatic,weightsSha:a.weightsSha,rejected:a.rejected},{automatic:b.automatic,weightsSha:b.weightsSha,rejected:b.rejected},message);
const nextRng=value=>{let x=value>>>0;x=(x^(x<<13))>>>0;x=(x^(x>>>17))>>>0;return (x^(x<<5))>>>0;};
function retina(image,width,height){const values=new Array(16).fill(0),counts=new Array(16).fill(0);for(let y=0;y<height;y+=4)for(let x=0;x<width;x+=4){const color=image[y*width+x],cell=Math.min(3,Math.floor(y*4/height))*4+Math.min(3,Math.floor(x*4/width));values[cell]+=(.2126*(color&255)+.7152*((color>>>8)&255)+.0722*((color>>>16)&255))/255;counts[cell]++;}return values.map((v,i)=>counts[i]?v/counts[i]:0);}
(async()=>{
 const native=bridge(),report={kind:'actual-WASM-dual-neural-routing',fullGraphs:true,limits:'Original diagnostic cartridges, technical retinal/button mapping, seeds 11/23; no commercial-game success or biological equivalence. Checkpoints preserve acquired topology/RNG, not live LIF/game phase.',rows:[]};
 try{for(const system of ['sega','snes']){
  let image=null,width=0,height=0,core;const callbacks={onFrame:(pixels,w,h)=>{image=pixels;width=w;height=h;}};
  if(system==='sega')core=await require(path.join(assets,'sega-core.js')).create(callbacks,require(path.join(cores,'sega/genplus.js')),{wasmBinary:fs.readFileSync(path.join(cores,'sega/genplus.wasm'))});
  else core=await require(path.join(assets,'retro-core.js')).create(system,callbacks,require(path.join(cores,system,'core.js')),{wasmBinary:fs.readFileSync(path.join(cores,system,'core.wasm'))});
  assert.equal(core.twoPlayerSupported,true);const rom=Uint8Array.from(Buffer.from(require(path.join(assets,'demo-'+system+'.json')).base64,'base64')),romHash=crypto.createHash('sha256').update(rom).digest('hex');core.loadROM(rom);for(let frame=0;frame<30;frame++)core.frame();const snapshot=core.toJSON();assert(image&&width&&height);
  const start=await native.call({op:'init',system,romHash,p1Model:'flywire-v783',p2Model:'male-cns-v1.0'});assert.equal(start.fullGraphs,true);assert.equal(start.graphShared,false);assert.deepEqual(start.states.map(s=>s.id),['p1','p2']);assert.equal(start.states[0].neurons,138639);assert.equal(start.states[1].neurons,165122);assert.equal(start.states[1].baseEdges,25563197);
  const observe=()=>retina(image,width,height),sample=agents=>native.call({op:'sample',retina:observe(),agents});const readSega=port=>{const address=(port-1)*2,value=(core.cpu.mem[address]<<8)|core.cpu.mem[address+1];return value&32768?value-65536:value;};const hardware=port=>system==='sega'?readSega(port):core.cpu.mem[(port===1?0x10:0x30)+7]-core.cpu.mem[(port===1?0x10:0x30)+6];
  const a=await sample([request('p1','train'),request('p2','train')]),masks=a.agents.map(actor=>actor.decision.mask);assert.deepEqual(masks,[128,64],'fixed first seeds select opposing permitted masks through production actor code');assert(a.agents.every(actor=>Number.isFinite(actor.wallMs)&&actor.spikes>=0));const initial=[hardware(1),hardware(2)];
  for(let port=1;port<=2;port++)for(let bit=0;bit<12;bit++)masks[port-1]&(1<<bit)?core.buttonDown(port,bit):core.buttonUp(port,bit);const frames=6,emulatorStarted=performance.now();for(let frame=0;frame<frames;frame++)core.frame();const emulatorMs=performance.now()-emulatorStarted;
  const raw=[hardware(1),hardware(2)],delta=system==='sega'?raw.map((v,i)=>v-initial[i]):raw;assert.deepEqual(delta,system==='sega'?[frames,-frames]:[1,-1],'real cartridge reads commands on independent hardware ports');
  if(system==='snes'){const serial=[8,0,1,3,4,5,6,7,9,10,11,2];for(let port=1;port<=2;port++)for(let bit=0;bit<12;bit++)assert.equal(core.cpu.mem[(port===1?0x10:0x30)+serial[bit]],Number(Boolean(masks[port-1]&(1<<bit))),'SNES physical serial bit P'+port+' bit '+bit);}
  const reward=delta.map(v=>system==='sega'?v*.1:v),outcome=i=>({id:a.agents[i].decision.id,mask:masks[i],frames,gameSeconds:frames/core.fps,reward:reward[i],valid:true});
  const b=await sample([request('p1','train',outcome(0)),request('p2','train')]);assert.equal(b.states[0].automatic,a.states[0].automatic+1);sameAcquired(b.states[1],a.states[1],'P1 reward preserves P2 acquired topology/outcome counters');assert.equal(b.states[1].rng,nextRng(a.states[1].rng),'P2 advances only its own new action RNG');
  const c=await sample([request('p1','train'),request('p2','train',outcome(1))]);sameAcquired(c.states[0],b.states[0],'P2 reward preserves P1 acquired topology/outcome counters');assert.equal(c.states[0].rng,nextRng(b.states[0].rng),'P1 advances only its own new action RNG');assert.equal(c.states[1].automatic,a.states[1].automatic+1);assert.notEqual(c.states[0].weightsSha,a.states[0].weightsSha,'actual retina/CPU activity/P1 hardware reward update Wexo');assert.notEqual(c.states[1].weightsSha,a.states[1].weightsSha,'actual retina/CPU activity/P2 hardware reward update its own Wexo');
  const frozen=await sample([request('p1','eval',outcome(0),true),request('p2','eval',outcome(1),true)]);for(let i=0;i<2;i++)sameLearning(frozen.states[i],c.states[i],'frozen evaluation ignores rewards and preserves independent actor RNG');
  const resumed=await native.call({op:'checkpoint',id:'p1'});sameLearning(resumed.states[1],frozen.states[1],'reloading P1 does not reset P2 learning');for(const key of ['automatic','rng','weightsSha'])assert.equal(resumed.states[0][key],frozen.states[0][key],'checkpoint preserves '+key);const after=await sample([request('p1','eval'),request('p2','eval')]);for(let i=0;i<2;i++)sameLearning(after.states[i],resumed.states[i],'resumed actor supports immutable evaluation');
  const releaseBefore=[hardware(1),hardware(2)];for(let port=1;port<=2;port++)for(let bit=0;bit<12;bit++)core.buttonUp(port,bit);for(let frame=0;frame<3;frame++)core.frame();assert.deepEqual([hardware(1),hardware(2)],system==='sega'?releaseBefore:[0,0],'both controllers release without stuck inputs');core.fromJSON(snapshot);assert.equal(core.mask|core.mask2,0);
  const engineMs=[a,b,c,frozen,after].map(batch=>batch.agents.reduce((n,agent)=>n+agent.wallMs,0));report.rows.push({system,seeds:[11,23],masks,reward,hardwareDelta:delta,frames,emulatorMs,meanPairCpuWindowMs:engineMs.reduce((a,b)=>a+b,0)/engineMs.length,maxPairCpuWindowMs:Math.max(...engineMs),pairGraphAndEnginesBytesEstimate:start.pairGraphAndEnginesBytesEstimate,p1:c.states[0],p2:c.states[1]});console.log('PASS: '+system+' actual WASM → shared retina → separate full CPU models → P1/P2 hardware → targeted Wexo rewards → frozen eval → P1-only durable resume');
 }
 const Retro=require(path.join(assets,'retro-core.js')),gb=await Retro.create('gb',{},require(path.join(cores,'gb/core.js')),{wasmBinary:fs.readFileSync(path.join(cores,'gb/core.wasm'))});gb.loadROM(Uint8Array.from(Buffer.from(require(path.join(assets,'demo-gb.json')).base64,'base64')));assert.equal(gb.twoPlayerSupported,false);gb.buttonDown(2,7);assert.equal(gb.mask2,0);console.log('PASS: actual GB core exposes no independent P2; UI rejects before native allocation in its separate coordinator test');
 if(process.env.DUAL_REPORT)fs.writeFileSync(process.env.DUAL_REPORT,JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
 }finally{await native.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
