package org.node.flyconsole;
import org.json.*;import java.io.*;import java.nio.file.*;import java.util.*;
public final class FdbCheckpointCheck {
 static void require(boolean b,String s){if(!b)throw new AssertionError(s);}
 static GraphDelta copy(GraphDelta d){GraphDelta c=new GraphDelta(30);for(GraphDelta.Edge e:d.edges())c.addEdge(e.source,e.target,e.weight);for(GraphDelta.Edge e:d.deltas())c.addWeightDelta(e.source,e.target,e.weight);return c;}
 public static void main(String[] args)throws Exception{
  Graph g=FdbLearningCheck.graph();int[] sources=FdbLearningCheck.sources(),targets=FdbLearningCheck.targets();GraphDelta d=new GraphDelta(30);FdbLearning a=FdbLearningCheck.learner(g,d);a.seed(321);
  for(int i=0;i<60;i++){FdbLearning.Decision decision=a.decide("first-"+i,FdbLearningCheck.active(),new int[]{0,1},4095,100,.1,true,null);a.feedback(decision.id,decision.mask,decision.mask==1?1:-1,.1,6,true,false,null);}
  JSONObject state=FdbCheckpoint.save(a,g,sources,targets);GraphDelta resumed=copy(d);FdbLearning b=FdbLearningCheck.learner(g,resumed);FdbCheckpoint.restore(b,new JSONObject(state.toString()),g,sources,targets);
  require(state.toString().equals(FdbCheckpoint.save(b,g,sources,targets).toString()),"exact learning state roundtrip");a.boundary();b.boundary();
  for(int i=0;i<40;i++){FdbLearning.Decision da=a.decide("next-"+i,FdbLearningCheck.active(),new int[]{0,1},4095,100,.1,true,null),db=b.decide("next-"+i,FdbLearningCheck.active(),new int[]{0,1},4095,100,.1,true,null);require(da.mask==db.mask,"restored actor RNG");double reward=da.mask==1?1:-1;a.feedback(da.id,da.mask,reward,.1,6,true,false,null);b.feedback(db.id,db.mask,reward,.1,6,true,false,null);}
  require(FdbCheckpoint.save(a,g,sources,targets).toString().equals(FdbCheckpoint.save(b,g,sources,targets).toString()),"continued learning retains utility and traces");for(GraphDelta.Edge e:d.edges())require(FdbLearningCheck.weight(resumed,e.source,e.target)==e.weight,"continued topology weights");
  String before=FdbCheckpoint.save(b,g,sources,targets).toString();JSONObject corrupt=new JSONObject(state.toString());corrupt.getJSONArray("traces").put(corrupt.getJSONArray("traces").getJSONObject(0));boolean rejected=false;try{FdbCheckpoint.restore(b,corrupt,g,sources,targets);}catch(Exception expected){rejected=true;}require(rejected&&before.equals(FdbCheckpoint.save(b,g,sources,targets).toString()),"invalid checkpoint cannot partially mutate learner");
  JSONObject legacy=new JSONObject(state.toString()).put("version",1);FdbLearning old=FdbLearningCheck.learner(g,copy(d));old.seed(77);FdbCheckpoint.restore(old,legacy,g,sources,targets);require(old.observations()==state.getLong("observations")&&old.traces().isEmpty()&&old.rng()==77,"v1 migrates counters, no fabricated eligibility");
  File root=Files.createTempDirectory("fdb-set").toFile();LayerSetStore store=new LayerSetStore(root);String id=UUID.randomUUID().toString();JSONArray in=new JSONArray(),out=new JSONArray();for(int i:sources)in.put(Long.toString(g.ids[i]));for(int i:targets)out.put(Long.toString(g.ids[i]));
  JSONObject config=new JSONObject().put("inputs",in).put("outputs",out).put("fdb",JSONObject.NULL),set=new JSONObject().put("type","fly-layer-set").put("layerVersion",1).put("id",id).put("name","FDB continuation").put("notes","").put("system","sega").put("romHash",String.format("%064d",1)).put("graph",new JSONObject().put("sha256",g.fingerprint())).put("createdAt",1).put("updatedAt",2).put("configuration",config).put("key",new JSONObject().put("configuration",new JSONObject(config.toString())).toString()).put("profile",new JSONObject()).put("runtime",new JSONObject()).put("policy",new JSONObject().put("updates",0).put("episodes",0)).put("journal",new JSONArray());store.save(set);
  JSONObject fdb=new JSONObject().put("version",2).put("graph_sha256",g.fingerprint()).put("deltas",new JSONArray()).put("edges",new JSONArray().put(new JSONObject().put("source","1").put("target","17").put("weight",22))).put("learningState",state);
  store.updateFdb(id,"sega",set.getString("romHash"),g.fingerprint(),in,out,fdb);JSONObject loaded=new LayerSetStore(root).get(id);require(loaded.getInt("layerVersion")==2&&loaded.getJSONObject("configuration").getJSONObject("fdb").toString().equals(fdb.toString()),"atomic full topology survives reopen");require(!new JSONObject(loaded.getString("key")).getJSONObject("configuration").getJSONObject("fdb").has("learningState"),"portable signature excludes temporal state");
  before=loaded.toString();rejected=false;try{store.updateFdb(id,"gb",set.getString("romHash"),g.fingerprint(),in,out,fdb);}catch(Exception expected){rejected=true;}require(rejected&&before.equals(store.get(id).toString()),"mismatching platform cannot corrupt active preset");for(File file:root.listFiles())file.delete();root.delete();
  System.out.println("PASS: FDB v2 exact checkpoint, reproducible resumed training, v1 migration, malformed-state rollback and atomic Layer Set topology / identity");
 }
}
