'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const Learner=require('../app/src/main/assets/lab/learner.js');
const source=fs.readFileSync('app/src/main/assets/lab/lab.js','utf8');
const f=Array(45).fill(0);f[0]=1;
const policy=new Learner(7);policy.setActions([0,4,8,12,1,129]);
policy.weights[2][0]=19;policy.weights[3][0]=20;
policy.setAllowedMask(243);policy.epsilon=1;
for(let i=0;i<1000;i++)assert.equal(policy.actions[policy.choose(f,true)]&12,0,'exploration cannot select forbidden actions');
assert.equal(policy.actions[policy.choose(f,false)]&12,0,'greedy policy cannot select highest forbidden Q');
const saved=JSON.stringify(policy.weights);policy.setAllowedMask(255);assert.equal(policy.actions[policy.choose(f,false)],12);assert.equal(JSON.stringify(policy.weights),saved,'ownership mode preserves learned weights');
policy.setAllowedMask(247);policy.weights[1][0]=20;policy.weights[3][0]=19;assert.equal(policy.actions[policy.choose(f,false)],4,'Sega C remains an allowed game button');
const events=[],mode={value:'blocked'};
const state={loaded:true,labPlatform:'nes',$:()=>mode,manualMask:0,brainMask:12,gmodeMode:'off',appliedMask:0,appliedHumanMask:0,appliedAgentMask:0,nes:{buttonDown:(p,b)=>events.push(['down',p,b]),buttonUp:(p,b)=>events.push(['up',p,b])}};
vm.createContext(state);vm.runInContext(source.slice(source.indexOf('function agentAllowedMask'),source.indexOf('function rgbaAndRetina')),state);
state.updateButtons();assert.deepEqual(events,[],'raw neural Start/Select blocked at the final controller boundary');
state.manualMask=12;state.updateButtons();assert.deepEqual(events,[['down',1,2],['down',1,3]],'human Start/Select preserved');
state.releasePorts();events.length=0;state.gmodeMode='coop';state.brainMask=140;state.updateButtons();assert.deepEqual(events,[['down',1,2],['down',1,3],['down',2,7]],'P2 agent filtered; P1 human unaffected');
state.releasePorts();events.length=0;state.gmodeMode='coop-reverse';state.updateButtons();assert.deepEqual(events,[['down',2,2],['down',2,3],['down',1,7]],'swapped ports preserve ownership');
state.releasePorts();events.length=0;state.labPlatform='sega';state.gmodeMode='off';state.manualMask=0;state.brainMask=12;state.updateButtons();assert.deepEqual(events,[['down',1,2]],'Sega C is not Select');
state.releasePorts();events.length=0;mode.value='auto';state.updateButtons();assert.deepEqual(events,[['down',1,2],['down',1,3]],'auto retains current behavior');
console.log('PASS: production neuron/readout control masks, human ownership, both GMode ports, Sega C and SARSA greedy/exploration without weight loss');
