'use strict';
const assert=require('node:assert/strict');
const Learner=require('../app/src/main/assets/lab/learner.js');
const fs=require('node:fs');
const actions=[0,1,2,16,32,64,128,129,17,3,65,33,66,130,18,34,19,67,131,35,4,8];
const a=new Learner(1),b=new Learner(1);a.setActions(actions);b.setActions(actions);
assert.equal(a.preset(17),true);assert.equal(b.preset(17),true);
assert.deepEqual(a.weights,b.weights,'same seed must produce the same structural prior');
const brightRight=new Array(16).fill(0);brightRight[3]=1;
const right=a.features(brightRight,new Array(8).fill(0));
const brightLeft=new Array(16).fill(0);brightLeft[0]=1;
const left=a.features(brightLeft,new Array(8).fill(0));
assert(a.q(right,a.actions.indexOf(128))>a.q(right,a.actions.indexOf(64)),'right-side visual activity should bias the right action');
assert(a.q(left,a.actions.indexOf(64))>a.q(left,a.actions.indexOf(128)),'left-side visual activity should bias the left action');
a.updates=1;const learned=JSON.stringify(a.weights);assert.equal(a.preset(17),false);assert.equal(JSON.stringify(a.weights),learned,'preset must not replace a trained policy');
const handcrafted=new Learner(2);handcrafted.setActions(actions);handcrafted.weights[0][1]=.25;const custom=JSON.stringify(handcrafted.weights);assert.equal(handcrafted.preset(17),false);assert.equal(JSON.stringify(handcrafted.weights),custom,'nonzero policy weights are preserved even before the update counter advances');
assert(a.epsilon>0&&a.alpha>0,'the existing SARSA adapter remains trainable after applying the preset');
const html=fs.readFileSync('app/src/main/assets/lab/index.html','utf8');
const manifest=fs.readFileSync('app/src/main/AndroidManifest.xml','utf8');
assert(html.includes('id="gmodeLaunch"')&&html.includes('id="gameExit"')&&html.includes('id="gameSettings"')&&html.includes('id="gameConnect"'),'dedicated game mode must expose launch, exit, settings and connect controls');
assert(html.includes('body.game-mode .screen canvas{height:100%;width:auto;')&&html.includes('object-fit:contain'),'landscape game view must preserve the ROM aspect ratio');
assert(manifest.includes('android:screenOrientation="fullUser"')&&manifest.includes('android:configChanges="orientation|screenSize|keyboardHidden"'),'rotation must preserve the Activity and live session');
console.log('PASS: deterministic 2P starter prior, spatial direction bias, and protection of trained readout weights');
